# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MZFormSheetPresentationController Swift Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MZFormSheetPresentationController Swift Example
    pod 'MZAppearance'
    pod 'JGMethodSwizzler'
    pod 'MZFormSheetPresentationController'

end
